version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
      #- "9299:9299"
      #- "9399:9399"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      #- "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # TODO it should wait for logstash to be ready.
  filebeat:
    build:
      context: filebeat/
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
      - ./filebeat/test-data/logs/nginx:/var/log/nginx:ro
      - ./filebeat/test-data/logs/system.log:/var/log-host/system.log:ro
      - ./filebeat/test-data/logs/celery:/var/log/celery:ro
      - /Users/nimiq/workspace/inspire-next/celery.log:/var/log/celery-live/celery.log:ro

    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    #ports:
      #- "5000:5000"
      #- "5044:5044"
    # With debug output:

    # Delete the registry and re-fetch everything.
    # command: bash -c "rm -f /usr/share/filebeat/data/registry && filebeat -e -d publish"
    command: bash -c "filebeat -e -d publish"

    # Without debug output:
    # command: bash -c "rm -f /usr/share/filebeat/data/registry && filebeat -e"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - elk
    depends_on:
      - elasticsearch


#  ubuntu:
#    image: ubuntu:18.04
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch



networks:

  elk:
    driver: bridge
