# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

# Pre-installed plugins:
# RUN elasticsearch-plugin install ingest-geoip
# RUN elasticsearch-plugin install ingest-user-agent
